
client:
  react:
    server: http://localhost:3000

server:
  # 8081은 local용
#  port: 8081
#  8443과 ssl 설정은 서버 배포용
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: yourday1108
#  8443과 ssl 설정은 서버 배포용
  servlet:
#    context-path: /api
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  profiles:
    active: alpha

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k7d209.p.ssafy.io:3306/userDB?serverTimezone=Asia/Seoul
    username: gumid209
    password: yourday1108
  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MySQL8Dialect  # ??? ??? ?? ?????? ??? ?????.
        show_sql: false  # sql ??? ?????.
        format_sql: false  # sql query formatting
        use_sql_comments: false  # sql ??? ????? ?????.

  security:
    user:
      name: user
      password: pw
    oauth2:
      client:
        registration:
          google:
            client-id: 282969920966-b1gjl6hdc38uek25euqcl82c3vse5hn9.apps.googleusercontent.com
            client-secret: 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
#            redirect-uri: https://k7d209.p.ssafy.io/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: a04a1ff92991fc9f2ca74a09006f3d3c
            client-secret: z4rkEeqA5asrboM2pkXviLndwYOJvGjw
            redirect-uri: https://k7d209.p.ssafy.io/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  jwt:
    secret: gumid209freesubjectprojectyourdayletsgo

#  redis:
#    host: Standalone Redis 호스트
#    port: Standalone Redis 포트

  redis:
    host: k7d209.p.ssafy.io
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


#springdoc:
#  api-docs:
#    enabled: false
#  swagger-ui:
#    enabled: false

#cloud:
#  aws:
#    credentials:
#      instanceProfile: false
#      accessKey: AKIA2MWS3LH5NXTGMOZU
#      secretKey: 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
#    s3:
#      bucket: gumi-d209
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
